learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls'))
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path
from . import views


app_name = 'learning_logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topic/<int:id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:id>/', views.edit_entry, name='edit_entry'),
    path('delete_entry/<int:id>/', views.delete_entry, name='delete_entry'),
    path('delete_topic/<int:id>/', views.delete_topic, name='delete_topic'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """ a topic the user is learning about """
    text = models.CharField(max_length=200)
    date_add = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """ something specific learnt about a topic """
    topic_id = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_add = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}...."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': 'Topic Title'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

template_name = r"learning_logs/index.html"


def index(request):
    """ the home page for learning log """
    return render(request, r'learning_logs/index.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(user=request.user).order_by('date_add')
    context = {'topics': topics}
    return render(request, r'learning_logs/topics.html', context)


@login_required
def topic(request, id):
    try:
        entries = Entry.objects.filter(topic_id=id).order_by('date_add')
        topic = Topic.objects.get(id=id)
        check_topic_owner(topic, request)
        context = {'entries': entries, 'topic': topic}
    except Exception:
        raise Http404
    return render(request, r'learning_logs/topic.html', context)


def check_topic_owner(topic, request):
    if topic.user != request.user:
        raise Http404


@login_required
def new_topic(request):
    """ add new topic """
    if request.method != 'POST':
        """ Create blank form """
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.user = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, r'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, id):
    """ add new entry """
    topic = Topic.objects.get(id=id)
    check_topic_owner(topic, request)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic_id = topic
            new_entry.save()
            return redirect('learning_logs:topic', id=id)
    context = {'form': form, 'topic': topic}
    return render(request, r'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, id):
    entry = Entry.objects.get(id=id)
    topic = entry.topic_id
    check_topic_owner(topic, request)
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', id=topic.id)
    context = {'entry': entry, 'form': form, 'topic': topic}
    return render(request, r'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, id):
    entry = Entry.objects.get(id=id)
    if not entry:
        raise Http404
    topic = entry.topic_id
    check_topic_owner(topic, request)
    entry.delete()
    return redirect('learning_logs:topic', id=topic.id)


@login_required
def delete_topic(request, id):
    topic = Topic.objects.get(id=id)
    if not topic:
        raise Http404
    check_topic_owner(topic, request)
    topic.delete()
    return redirect('learning_logs:topics')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """ Register new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    context = {'form': form}
    return render(request, r'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics'%}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% extends 'learning_logs/base.html' %}
    {% load bootstrap4 %}

    {% block page_header %}
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    {% endblock page_header %}

    {% block content %}
        <p>Edit entry:</p>
        <form  class="form" action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-primary">Save Changes</button>
            {% endbuttons %}
        </form>
    {% endblock content%}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% extends "learning_logs/base.html" %}
    {% block page_header %}
        <div class="jumbotron">
            <h1 class="display-3">Track your learning  .</h1>
            <p class="lead">
                Make your own Learning Log, and keep a list of the
                topics you're learning about. Whenever you learn something new
                about a topic, make an entry summarizing what you've learned.</p>
            {% if not user.is_authenticated %}
                <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">
                    Register &raquo;
                </a>
            {% endif %}
        </div>
    {% endblock page_header %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% extends 'learning_logs/base.html' %}
    {% load bootstrap4 %}

    {% block page_header %}
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    {% endblock page_header %}

    {% block content %}
        <p>Add new entry</p>
        <form class="form"  action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-primary">Add Entry</button>
            {% endbuttons %}
        </form>
    {% endblock content%}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap4 %}

    {% block page_header %}
        <h4>Add a new topic:</h4>
    {% endblock page_header %}


    {% block content %}
        <form  class="form" action="{% url 'learning_logs:new_topic' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-primary">Add Topic</button>
            {% endbuttons %}
        </form>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% extends "learning_logs/base.html" %}

    {% block page_header %}
        <h3>{{ topic }}</h3>
        <small>
            <a href="{% url 'learning_logs:delete_topic' topic.id %}">
                Delete topic
            </a>
        </small>
    {% endblock page_header %}

    {% block content %}
        <p>
            <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
        </p>
    {% for entry in entries %}
        <div class="card mb-3">
            <h6 class="card-header">
                {{ entry.date_add|date:'M d, Y H:i' }}
                <small>
                    <a class="btn btn-sm btn-primary" role="button" href="{% url 'learning_logs:edit_entry' entry.id %}">
                          Edit entry
                    </a>
                </small>
                <span>-</span>
                <small>
                    <a class="btn btn-sm btn-primary" role="button" href="{% url 'learning_logs:delete_entry' entry.id %}">
                        Delete entry
                    </a>
                </small>
            </h6>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<body>
    {% extends "learning_logs/base.html" %}

    {% block page_header %}
        <h1>Topics</h1>
    {% endblock page_header %}

    {% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h5> <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </h5>
            </li>
        {% empty %}
           <h6> <li>No topics have been added yet</li> </h6>
        {% endfor%}
    </ul>
    <h6> <a href="{% url 'learning_logs:new_topic' %}">Add new topic</a> </h6>
    {% endblock content %}
</body>
</html>